name: build docs and deploy

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v1
    - 
      name: Build
      run: |
        mkdir -p docs
        chmod 777 -R ./docs/
        docker run --rm --volume="$PWD:/srv/jekyll" -i jekyll/builder:3.8 jekyll build
    - 
      name: Deploy
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}users.noreply.github.com"
        git add -A
        git commit -m "Automated docs build" --allow-empty
        REMOTE="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git push --force "${REMOTE}" HEAD:master
